# Generated by Django 4.2.16 on 2024-09-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_create_by_wpblog_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpblogsite',
            name='wp_blog_id',
            field=models.BigIntegerField(),
            preserve_default=False,
        ),
    ]
