# Generated by Django 4.2.16 on 2024-09-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WpSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('wp_user', models.CharField(max_length=200)),
                ('wp_password', models.CharField(max_length=200)),
            ],
        ),
    ]
