# Generated by Django 4.2.16 on 2024-09-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wp_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wpsite',
            old_name='wp_user',
            new_name='wp_username',
        ),
    ]
